Meteor.startup ->
	if Meteor.users.find().count() == 0
    options =
      email: "frederick.bouchard88@gmail.com"
      password: "627dada"
      roles: ['admin']
    Accounts.createUser options

	if Categories.find().count() == 0
		Categories.insertTranslations {name: "Computer", systemId: "PC"}, {fr: {name: "Ordinateur"}}
		Categories.insertTranslations {name: "Mobile", systemId: "MO"}
		Categories.insertTranslations {name: "Home", systemId: "HO"}, {fr: {name: "Maison"}}
		Categories.insertTranslations {name: "Office", systemId: "OF"}, {fr: {name: "Bureau"}}
		Categories.insertTranslations {name: "Car", systemId: "CA"}, {fr: {name: "Voiture"}}
		Categories.insertTranslations {name: "Gadgets", systemId: "GA"}

	if SubCategories.find().count() == 0
		SubCategories.insertTranslations {name: "RAM Memory", systemId: "MEM", catRel: ["PC"]}, {fr: {name: "Mémoire vive"}}
		SubCategories.insertTranslations {name: "External Hard Drives", systemId: "EHD", catRel: ["PC"]}, {fr: {name: "Disque dur externe"}}
		SubCategories.insertTranslations {name: "Backup solutions", systemId: "BUS", catRel: ["PC"]}, {fr: {name: "Solutions de sauvegarde"}}
		SubCategories.insertTranslations {name: "Networking", systemId: "NET", catRel: ["PC"]}, {fr: {name: "Réseautique"}}
		SubCategories.insertTranslations {name: "Media (CD/DVD/BlueRay)", systemId: "MED", catRel: ["PC"]}, {fr: {name: "Média (CD/DVD/BlueRay)"}}
		SubCategories.insertTranslations {name: "Optical wireless mice", systemId: "OWM", catRel: ["PC"]}, {fr: {name: "Souris sans-fil optique"}}
		SubCategories.insertTranslations {name: "I/O cards", systemId: "IOC", catRel: ["PC"]}, {fr: {name: "Cartes I/O"}}
		SubCategories.insertTranslations {name: "Cables", systemId: "CAB", catRel: ["PC"]}, {fr: {name: "Câbles"}}
		SubCategories.insertTranslations {name: "USB drives", systemId: "USB", catRel: ["PC"]}, {fr: {name: "Clés USB"}}
		SubCategories.insertTranslations {name: "Solid State Drive (SSD)", systemId: "SSD", catRel: ["PC"]}, {fr: {name: "Disque SSD"}}
		SubCategories.insertTranslations {name: "Compact Flash cards", systemId: "CFC", catRel: ["GA", "PC"]}, {fr: {name: "Cartes Compact Flash"}}
		SubCategories.insertTranslations {name: "SDHC cards", systemId: "SDC", catRel: ["GA", "PC"]}, {fr: {name: "Cartes SDHC"}}
		SubCategories.insertTranslations {name: "Micro SDHC cards", systemId: "MSD", catRel: ["MO", "GA"]}, {fr: {name: "Cartes micro SDHC"}}
		SubCategories.insertTranslations {name: "Card readers", systemId: "CRE", catRel: ["GA", "PC"]}, {fr: {name: "Lecteurs de carte"}}
		SubCategories.insertTranslations {name: "Home automations", systemId: "HOA", catRel: ["HO"]}, {fr: {name: "Automatisation de la maison"}}
		SubCategories.insertTranslations {name: "Alarm clocks / Radio", systemId: "ALA", catRel: ["HO"]}, {fr: {name: "Alarme / Radio"}}
		SubCategories.insertTranslations {name: "Cameras & Camcorders", systemId: "CAM", catRel: ["GA"]}, {fr: {name: "Appareil photos et vidéos"}}
		SubCategories.insertTranslations {name: "Conference systems", systemId: "CON", catRel: ["OF", "HO"]}, {fr: {name: "Système d'appels conférence"}}
		SubCategories.insertTranslations {name: "Dash Cameras", systemId: "DAC", catRel: ["CA"]}, {fr: {name: "Caméras de tableau de bord"}}
		SubCategories.insertTranslations {name: "Digital Picture Frame", systemId: "DPF", catRel: ["HO"]}, {fr: {name: "Cadre photos numériques"}}
		SubCategories.insertTranslations {name: "Docking Station", systemId: "DOC", catRel: ["HO", "MO"]}, {fr: {name: "Station mobile"}}
		SubCategories.insertTranslations {name: "DVD Players", systemId: "DVD", catRel: ["HO"]}, {fr: {name: "Lecteurs DVD"}}
		SubCategories.insertTranslations {name: "GPS", systemId: "GPS", catRel: ["CA"]}, {fr: {name: "Système GPS"}}
		SubCategories.insertTranslations {name: "Mobile Printers", systemId: "PRI", catRel: ["GA", "MO"]}, {fr: {name: "Imprimantes mobiles"}}
		SubCategories.insertTranslations {name: "Tablet PC", systemId: "TAB", catRel: ["MO", "PC"]}, {fr: {name: "Tablettes PC"}}
		SubCategories.insertTranslations {name: "Television accessories", systemId: "TVA", catRel: ["HO"]}, {fr: {name: "Accessoires de télévision"}}
		SubCategories.insertTranslations {name: "Televisions", systemId: "TVS", catRel: ["HO"]}, {fr: {name: "Télévisions"}}
		SubCategories.insertTranslations {name: "Wearable electronics", systemId: "WEE", catRel: ["GA", "MO"]}, {fr: {name: "Électronique prêt-à-porter"}}
		SubCategories.insertTranslations {name: "Everything for sound", systemId: "AUD", catRel: ["HO", "MO"]}, {fr: {name: "Tout pour le son"}}
		SubCategories.insertTranslations {name: "Bike / Toy / Pet lights", systemId: "BTL", catRel: ["GA"]}, {fr: {name: "Lumières vélo / animal / jouets"}}
		SubCategories.insertTranslations {name: "Flashlights", systemId: "FLA", catRel: ["GA", "HO"]}, {fr: {name: "Lumières de poche"}}
		SubCategories.insertTranslations {name: "LED Lighting", systemId: "LED", catRel: ["HO", "GA"]}, {fr: {name: "Lumières DEL"}}


	if Manufacturers.find().count() == 0
		Manufacturers.insert {name: "Allocacoc", systemId: "AL", thumb: "manuf/allocacoc.jpg"}
		Manufacturers.insert {name: "Aluratek", systemId: "AK", thumb: "manuf/aluratek.jpg"}
		Manufacturers.insert {name: "Apple", systemId: "AP", thumb: "manuf/apple.jpg"}
		Manufacturers.insert {name: "Autodrive", systemId: "AU", thumb: "manuf/autodrive.jpg"}
		Manufacturers.insert {name: "Battery-Biz", systemId: "BA", thumb: "manuf/batterybizz.png"}
		Manufacturers.insert {name: "Beewi", systemId: "BE", thumb: "manuf/beewi.jpg"}
		Manufacturers.insert {name: "Bose", systemId: "BO", thumb: "manuf/bose.jpg"}
		Manufacturers.insert {name: "Bracketron", systemId: "BR", thumb: "manuf/bracketron.png"}
		Manufacturers.insert {name: "Checkolite", systemId: "CH", thumb: "manuf/checkolite.jpg"}
		Manufacturers.insert {name: "Clickfree", systemId: "CL", thumb: "manuf/clickfree.jpg"}
		Manufacturers.insert {name: "Coby", systemId: "CO", thumb: "manuf/coby.jpg"}
		Manufacturers.insert {name: "Cogito", systemId: "CG", thumb: "manuf/cogito.jpg"}
		Manufacturers.insert {name: "Concept green", systemId: "CN", thumb: "manuf/concept-green.jpg"}
		Manufacturers.insert {name: "Cookoo", systemId: "CK", thumb: "manuf/cookoo.jpg"}
		Manufacturers.insert {name: "Craig", systemId: "CR", thumb: "manuf/craig.jpg"}
		Manufacturers.insert {name: "Dr.Battery", systemId: "DB", thumb: "manuf/dr.battery.jpg"}
		Manufacturers.insert {name: "DreamGear (iSound)", systemId: "DG", thumb: "manuf/isound.jpg"}
		Manufacturers.insert {name: "EP Memory", systemId: "EM", thumb: "manuf/ep_memory.gif"}
		Manufacturers.insert {name: "Eton", systemId: "ET", thumb: "manuf/eton.jpg"}
		Manufacturers.insert {name: "Fisher", systemId: "FI", thumb: "manuf/fisher.jpg"}
		Manufacturers.insert {name: "Hipstreet", systemId: "HI", thumb: "manuf/hipstreet.jpg"}
		Manufacturers.insert {name: "ICloth", systemId: "IC", thumb: "manuf/icloth.jpg"}
		Manufacturers.insert {name: "IHome", systemId: "IH", thumb: "manuf/ihome.jpg"}
		Manufacturers.insert {name: "IMicro", systemId: "IM", thumb: "manuf/imicro.jpg"}
		Manufacturers.insert {name: "Improv electronics", systemId: "IE", thumb: "manuf/improvelec.gif"}
		Manufacturers.insert {name: "Intel", systemId: "IN", thumb: "manuf/intel.jpg"}
		Manufacturers.insert {name: "IOMagic", systemId: "IO", thumb: "manuf/iomagic.png"}
		Manufacturers.insert {name: "IPopperz", systemId: "IP", thumb: "manuf/ipopperz.bmp"}
		Manufacturers.insert {name: "IRam", systemId: "IR", thumb: "manuf/iram.jpg"}
		Manufacturers.insert {name: "J5 Create", systemId: "JC", thumb: "manuf/j5create.jpg"}
		Manufacturers.insert {name: "Jasco", systemId: "JA", thumb: "manuf/jasco.jpg"}
		Manufacturers.insert {name: "Jawbone", systemId: "JW", thumb: "manuf/jawbone.jpg"}
		Manufacturers.insert {name: "JVC", systemId: "JV", thumb: "manuf/jvc.png"}
		Manufacturers.insert {name: "Kingston", systemId: "KI", thumb: "manuf/kingston.jpg"}
		Manufacturers.insert {name: "Konftel", systemId: "KO", thumb: "manuf/konftel.jpg"}
		Manufacturers.insert {name: "Lava", systemId: "LA", thumb: "manuf/lava.gif"}
		Manufacturers.insert {name: "Lenmar", systemId: "LE", thumb: "manuf/lenmar.png"}
		Manufacturers.insert {name: "Lexar", systemId: "LX", thumb: "manuf/lexar.png"}
		Manufacturers.insert {name: "Mancini", systemId: "MA", thumb: "manuf/mancini.jpg"}
		Manufacturers.insert {name: "Matricom", systemId: "MT", thumb: "manuf/matricom.png"}
		Manufacturers.insert {name: "Matrix Audio", systemId: "MX", thumb: "manuf/matrix_audio.png"}
		Manufacturers.insert {name: "Maxell", systemId: "ML", thumb: "manuf/maxell.png"}
		Manufacturers.insert {name: "Mimobot", systemId: "MI", thumb: "manuf/mimobot.jpg"}
		Manufacturers.insert {name: "Mykronoz", systemId: "MY", thumb: "manuf/mykronoz.png"}
		Manufacturers.insert {name: "Nite Ize", systemId: "NI", thumb: "manuf/nite_ize.jpg"}
		Manufacturers.insert {name: "Panasonic", systemId: "PA", thumb: "manuf/panasonic.jpg"}
		Manufacturers.insert {name: "Pentax", systemId: "PE", thumb: "manuf/pentax.jpg"}
		Manufacturers.insert {name: "Philips", systemId: "PH", thumb: "manuf/philips.png"}
		Manufacturers.insert {name: "Platinum", systemId: "PL", thumb: "manuf/platinum.jpg"}
		Manufacturers.insert {name: "Platinum Cables", systemId: "PC"}
		Manufacturers.insert {name: "Polar", systemId: "PO", thumb: "manuf/polar.jpg"}
		Manufacturers.insert {name: "Polaroid", systemId: "PR", thumb: "manuf/polaroid.png"}
		Manufacturers.insert {name: "Powerqube", systemId: "PW", thumb: "manuf/powerqube.png"}
		Manufacturers.insert {name: "PPA Int'l", systemId: "PP", thumb: "manuf/ppaintl.png"}
		Manufacturers.insert {name: "PQI", systemId: "PQ", thumb: "manuf/pqi.jpg"}
		Manufacturers.insert {name: "RCA", systemId: "RC", thumb: "manuf/rca.png"}
		Manufacturers.insert {name: "Roadmice", systemId: "RO", thumb: "manuf/roadmice.jpg"}
		Manufacturers.insert {name: "Roots", systemId: "RT", thumb: "manuf/roots.png"}
		Manufacturers.insert {name: "Sakar", systemId: "SK"}
		Manufacturers.insert {name: "Samsung", systemId: "SA", thumb: "manuf/samsung.png"}
		Manufacturers.insert {name: "Sandisk", systemId: "SD", thumb: "manuf/sandisk.jpg"}
		Manufacturers.insert {name: "Sierra", systemId: "SI"}
		Manufacturers.insert {name: "Sony", systemId: "SO", thumb: "manuf/sony.jpg"}
		Manufacturers.insert {name: "Standzout", systemId: "SZ", thumb: "manuf/standzout.jpg"}
		Manufacturers.insert {name: "Strongnfree", systemId: "SF"}
		Manufacturers.insert {name: "Super Talent", systemId: "ST", thumb: "manuf/super_talent.jpg"}
		Manufacturers.insert {name: "Tomtom", systemId: "TT", thumb: "manuf/tomtom.jpg"}
		Manufacturers.insert {name: "Toshiba", systemId: "TO", thumb: "manuf/toshiba.jpg"}
		Manufacturers.insert {name: "TP-Link", systemId: "TP", thumb: "manuf/tp-link.jpg"}
		Manufacturers.insert {name: "Transcend", systemId: "TR", thumb: "manuf/transcend.jpg"}
		Manufacturers.insert {name: "TripLogik", systemId: "TL", thumb: "manuf/triplogik.jpg"}
		Manufacturers.insert {name: "Turtle Beach", systemId: "TB", thumb: "manuf/turtle_beach.jpg"}
		Manufacturers.insert {name: "V7", systemId: "V7", thumb: "manuf/v7.jpg"}
		Manufacturers.insert {name: "Vivitar", systemId: "VI", thumb: "manuf/vivitar.gif"}
		Manufacturers.insert {name: "Whoosh", systemId: "WH", thumb: "manuf/whoosh.png"}
		Manufacturers.insert {name: "Winstar", systemId: "WI", thumb: "manuf/winstar.jpg"}
		Manufacturers.insert {name: "Xtreme", systemId: "XT", thumb: "manuf/xtreme.jpg"}

	if Products.find().count() == 0
		Products.insertTranslations {description: 'StoreJet 25S3 2.5" (USB 3.0 Enclosure)', modelNum: "TS0GSJ25S3", UPC: "760557828105", cost: "17.78", isInPromo: false, price: "30.00", qty: 3, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0001", thumb: "PCEHDTR0001.jpg"}, {fr: {description: 'StoreJet 25S3 2.5" USB 3.0'}}
		Products.insertTranslations {description: 'StoreJet 500GB 2.5" M3 USB3 External Hard Drive', modelNum: "TS500GSJ25M3", UPC: "760557818298", cost: "77.95", isInPromo: false, price: "92.00", qty: 18, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0002", thumb: "PCEHDTR0002.jpg"}, {fr: {description: 'StoreJet 2.5" M3 USB3 500Go Disque externe'}}
		Products.insertTranslations {description: 'StoreJet 500GB 2.5" H3P 2.5" USB3 External Hard Drive', modelNum: "TS500GSJ25H3P", UPC: "760557820673", cost: "78.57", isInPromo: false, price: "95.00", qty: 21, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0003", thumb: "PCEHDTR0003.jpg"}, {fr: {description: 'StoreJet 2.5" H3P 2.5" USB3 500Go Disque externe'}}
		Products.insertTranslations {description: 'StoreJet 1TB M3 External Hard Drive', modelNum: "TS1TSJ25M3", UPC: "760557821168", cost: "91.04", isInPromo: false, price: "105.00", qty: 33, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0004", thumb: "PCEHDTR0004.jpg"}, {fr: {description: 'StoreJet M3 1To Disque externe'}}
		Products.insertTranslations {description: 'StoreJet 750GB 2.5" M3 External Hard Drive', modelNum: "TS750GSJ25M3", UPC: "760557819363", cost: "98.68", isInPromo: false, price: "115.00", qty: 4, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0005", thumb: "PCEHDTR0005.jpg"}, {fr: {description: 'StoreJet 2.5" M3 750Go Disque externe'}}
		Products.insertTranslations {description: 'StoreJet 2TB 2.5" H3B - Blue', modelNum: "TS2TSJ25H3B", UPC: "106082", cost: "144.81", isInPromo: false, price: "165.00", qty: 2, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0006", thumb: "PCEHDTR0006.jpg"}, {fr: {description: 'StoreJet 2.5" H3B 2To Disque Externe - Bleu'}}
		Products.insertTranslations {description: 'StoreJet 2TB 2.5" H3P', modelNum: "TS2TSJ25H3P", UPC: "760557827009", cost: "144.81", isInPromo: false, price: "165.00", qty: 24, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0007", thumb: "PCEHDTR0007.jpg"}, {fr: {description: 'StoreJet 2.5" H3P 2To Disque Externe'}}
		Products.insertTranslations {description: 'StoreJet 2TB M3 External Hard Drive', modelNum: "TS2TSJ25M3", UPC: "760557829706", cost: "151.84", isInPromo: false, price: "175.00", qty: 7, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0008", thumb: "PCEHDTR0008.jpg"}, {fr: {description: 'StoreJet M3 2To Disque Externe'}}
		Products.insertTranslations {description: 'StoreJet 500 Portable SSD Thunderbolt for Mac 1TB', modelNum: "TS1TSJM500", UPC: "107294", cost: "939.21", isInPromo: false, price: "1005.00", qty: 0, catRel: "PC", subCatRel: "EHD", manufRel: "TR", systemId: "PCEHDTR0009", thumb: "PCEHDTR0009.jpg"}, {fr: {description: 'Storejet 500 SSD portable Thunderbolt pour Mac 1To'}}
		Products.insertTranslations {description: 'ClickFree C2 2.5" 500GB Portable - USB 3.0', modelNum: "CA3A05-2CBK9-F1S", UPC: "817048015237", cost: "63.44", isInPromo: true, price: "75.00", qty: 135, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0001", thumb: "PCBUSCL0001.jpg"}, {fr: {description: 'ClickFree C2 2.5" Portable 500Go - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C6 2.5" 500GB Portable - USB 3.0', modelNum: "CA3A05-6C", UPC: "817048013165", cost: "70.76", isInPromo: true, price: "85.00", qty: 2, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0002", thumb: "PCBUSCL0002.jpg"}, {fr: {description: 'ClickFree C6 2.5" Portable 500Go - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C2 2.5" 1TB Portable - USB 3.0', modelNum: "1027B3-1004-200", UPC: "817048011864", cost: "85.97", isInPromo: true, price: "100.00", qty: 75, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0003", thumb: "PCBUSCL0003.jpg"}, {fr: {description: 'ClickFree C2 2.5" Portable 1To - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C2 2.5" 1TB Portable - USB 3.0', modelNum: "CA3A10-2CBK9-F1S", UPC: "817048015244", cost: "88.63", isInPromo: true, price: "105.00", qty: 51, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0004", thumb: "PCBUSCL0004.jpg"}, {fr: {description: 'ClickFree C2 2.5" Portable 1To - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C6 2.5" 1TB Portable - USB 3.0', modelNum: "CA3A10-6CBK9-F1S", UPC: "817048013172", cost: "99.68", isInPromo: true, price: "120.00", qty: 13, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0005", thumb: "PCBUSCL0005.jpg"}, {fr: {description: 'ClickFree C6 2.5" Portable 1To - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C2 2.5" 500GB Portable - USB 3.0', modelNum: "CA3A05-2CBK9-F1S", UPC: "817048015237", cost: "101.73", isInPromo: false, price: "130.00", qty: 135, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0006", thumb: "PCBUSCL0006.jpg"}, {fr: {description: 'ClickFree C2 2.5" Portable 500Go - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C6 2.5" 500GB Portable - USB 3.0', modelNum: "CA3A05-6C", UPC: "817048013165", cost: "117.38", isInPromo: false, price: "135.00", qty: 2, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0007", thumb: "PCBUSCL0007.jpg"}, {fr: {description: 'ClickFree C6 2.5" Portable 500Go - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C6 2.5" 2TB Portable - USB 3.0', modelNum: "CA3C20-6CBK9-F2S", UPC: "817048013196", cost: "128.82", isInPromo: true, price: "160.00", qty: 20, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0008", thumb: "PCBUSCL0008.jpg"}, {fr: {description: 'ClickFree C6 2.5" Portable 2To - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C2 2.5" 1TB Portable - USB 3.0', modelNum: "CA3A10-2CBK9-F1S", UPC: "817048015244", cost: "133.03", isInPromo: false, price: "170.00", qty: 51, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0009", thumb: "PCBUSCL0009.jpg"}, {fr: {description: 'ClickFree C2 2.5" Portable 1To - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C2 2.5" 1TB Portable - USB 3.0', modelNum: "1027B3-1004-200", UPC: "817048011864", cost: "135.86", isInPromo: false, price: "175.00", qty: 75, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0010", thumb: "PCBUSCL0010.jpg"}, {fr: {description: 'ClickFree C2 2.5" Portable 1To - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C6 2.5" 1TB Portable - USB 3.0', modelNum: "CA3A10-6CBK9-F1S", UPC: "817048015343", cost: "148.68", isInPromo: false, price: "185.00", qty: 13, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0011", thumb: "PCBUSCL0011.jpg"}, {fr: {description: 'ClickFree C6 2.5" Portable 1To - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C2 2.5" 2TB Portable - USB 3.0', modelNum: "CA3C20-2CBK9-F2S", UPC: "817048015947", cost: "148.68", isInPromo: false, price: "185.00", qty: 1, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0012", thumb: "PCBUSCL0012.jpg"}, {fr: {description: 'ClickFree C2 2.5" Portable 2To - USB 3.0'}}
		Products.insertTranslations {description: 'ClickFree C6 2.5" 2TB Portable - USB 3.0', modelNum: "CA3C20-6CBK9-F2S", UPC: "817048013196", cost: "164.34", isInPromo: false, price: "205.00", qty: 20, catRel: "PC", subCatRel: "BUS", manufRel: "CL", systemId: "PCBUSCL0013", thumb: "PCBUSCL0013.jpg"}, {fr: {description: 'ClickFree C6 2.5" Portable 2To - USB 3.0'}}
		Products.insertTranslations {description: 'TP Link CPE510 Outdoor 5Ghz/300Mbps High power wireless access point', modelNum: "CPE510", UPC: "845973070922", cost: "77.31", isInPromo: false, price: "95.00", qty: 6, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0001", thumb: "PCNETTP0001.jpg"}, {fr: {description: "TP Link CPE510 Point d'accès sans-fil extérieur 5Ghz/300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WN725N 150Mbps Wireless N Nano USB Adapter', modelNum: "TL-WN725N", UPC: "845973050719", cost: "9.56", isInPromo: false, price: "20.00", qty: 55, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0002", thumb: "PCNETTP0002.jpg"}, {fr: {description: 'TP Link TL-WN725N Adaptateur sans-fil N Nano USB 150Mbps'}}
		Products.insertTranslations {description: 'TP Link TL-WN723N 150Mbps Wireless N Mini USB Adapter', modelNum: "TL-WN723N", UPC: "845973050559", cost: "12.87", isInPromo: false, price: "25.00", qty: 4, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0003", thumb: "PCNETTP0003.jpg"}, {fr: {description: 'TP Link TL-WN723N Adaptateur sans-fil N Mini USB 150Mbps'}}
		Products.insertTranslations {description: 'TP Link TL-WN823N 300Mbps Wireless N Mini USB Adapter', modelNum: "TL-WN823N", UPC: "845973050696", cost: "12.91", isInPromo: true, promoEnds: "10 sep 2015", price: "25.00", qty: 8, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0004", thumb: "PCNETTP0004.jpg"}, {fr: {description: 'TP Link TL-WN823N Adaptateur sans-fil N Mini USB 300Mbps'}}
		Products.insertTranslations {description: 'TP Link TL-WN722N 150Mbps High Gain Wireless USB Adapter', modelNum: "TL-WN722N", UPC: "845973050467", cost: "13.73", isInPromo: false, price: "30.00", qty: 6, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0005", thumb: "PCNETTP0005.jpg"}, {fr: {description: 'TP Link TL-WN722N Adaptateur sans-fil USB Haute Connexion 150Mbps'}}
		Products.insertTranslations {description: 'TP Link TL-WR740N 150Mbps Wireless N Router', modelNum: "TL-WR740N", UPC: "845973051334", cost: "17.17", isInPromo: false, price: "35.00", qty: 68, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0006", thumb: "PCNETTP0006.jpg"}, {fr: {description: "TP Link TL-WR740N Routeur sans-fil N 150Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WN823N 300Mbps Wireless N Mini USB Adapter', modelNum: "TL-WN823N", UPC: "845973050696", cost: "17.17", isInPromo: false, price: "35.00", qty: 8, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0007", thumb: "PCNETTP0007.jpg"}, {fr: {description: "TP Link TL-WN823N Adaptateur sans-fil N Mini USB 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WN821N 300Mbps Wireless N USB Adapter', modelNum: "TL-WN821N", UPC: "845973050368", cost: "17.17", isInPromo: false, price: "35.00", qty: 10, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0008", thumb: "PCNETTP0008.jpg"}, {fr: {description: "TP Link TL-WN821N Adaptateur sans-fil N USB 300Mbps"}}
		Products.insertTranslations {description: 'TP Link Archer T2U AC600 Wireless Dual Band USB Adapter', modelNum: "Archer T2U", UPC: "845973050856", cost: "18.93", isInPromo: true, promoEnds: "10 sep 2015", price: "40.00", qty: 109, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0009", thumb: "PCNETTP0009.jpg"}, {fr: {description: "TP Link Archer T2U AC600 Adaptateur USB Bi-bande"}}
		Products.insertTranslations {description: 'TP Link TL-WR702N 150Mbps Wireless N Nano Router', modelNum: "TL-WR702N", UPC: "845973051785", cost: "19.74", isInPromo: false, price: "45.00", qty: 40, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0010", thumb: "PCNETTP0010.jpg"}, {fr: {description: "TP Link TL-WR702N Routeur sans-fil N Nano 150Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WN822N 300Mbps High Gain Wireless USB Adapter', modelNum: "TL-WN822N", UPC: "845973050542", cost: "19.74", isInPromo: false, price: "45.00", qty: 6, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0011", thumb: "PCNETTP0011.jpg"}, {fr: {description: "TP Link TL-WN822N Adaptateur sans-fil USB Haute Connexion 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WR841N 300Mbps Wireless N Router', modelNum: "TL-WR841N", UPC: "845973051242", cost: "20.85", isInPromo: true, promoEnds: "10 sep 2015", price: "45.00", qty: 54, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0012", thumb: "PCNETTP0012.jpg"}, {fr: {description: "TP Link TL-WR841N Routeur sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WR841N 300Mbps Wireless N Router', modelNum: "TL-WR841N", UPC: "845973051242", cost: "24.04", isInPromo: false, price: "45.00", qty: 54, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0013", thumb: "PCNETTP0013.jpg"}, {fr: {description: "TP Link TL-WR841N Routeur sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WR700N 150Mbps Wireless N Mini Pocket Router', modelNum: "TL-WR700N", UPC: "845973051631", cost: "25.77", isInPromo: false, price: "45.00", qty: 18, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0014", thumb: "PCNETTP0014.jpg"}, {fr: {description: "TP Link TL-WR700N Routeur sans-fil de poche N Mini 150Mbps"}}
		Products.insertTranslations {description: 'TP Link Archer T2U AC600 Wireless Dual Band USB Adapter', modelNum: "Archer T2U", UPC: "845973050856", cost: "25.77", isInPromo: false, price: "45.00", qty: 109, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0015", thumb: "PCNETTP0015.jpg"}, {fr: {description: "TP Link Archer T2U AC600 Adaptateur USB Bi-bande"}}
		Products.insertTranslations {description: 'TP Link TL-WR941ND Wireless N Router', modelNum: "TL-WR941ND", UPC: "845973051273", cost: "26.89", isInPromo: true, promoEnds: "10 sep 2015",price: "45.00", qty: 20, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0016", thumb: "PCNETTP0016.jpg"}, {fr: {description: "TP Link TL-WR941ND Routeur sans-fil N"}}
		Products.insertTranslations {description: 'TP Link TL-WR841ND Wireless N Router 300Mbps', modelNum: "TL-WR841ND", UPC: "845973051280", cost: "28.34", isInPromo: false, price: "45.00", qty: 108, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0017", thumb: "PCNETTP0017.jpg"}, {fr: {description: "TP Link TL-WR841ND Routeur sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WA701ND Wireless N Access Point 150Mbps', modelNum: "TL-WA701ND", UPC: "845973051402", cost: "30.05", isInPromo: false, price: "50.00", qty: 2, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0018", thumb: "PCNETTP0018.jpg"}, {fr: {description: "TP Link TL-WA701ND Point d'acces sans-fil N 150Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WR940N Wireless N Pocket Router 300Mbps', modelNum: "TL-WR940N", UPC: "845973051464", cost: "30.05", isInPromo: false, price: "50.00", qty: 58, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0019", thumb: "PCNETTP0019.jpg"}, {fr: {description: "TP Link TL-WR940N Routeur sans-fil de poche N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WN8200ND High Power Wireless USB Adapter 300Mbps', modelNum: "TL-WN8200ND", UPC: "845973050740", cost: "30.05", isInPromo: false, price: "50.00", qty: 6, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0020", thumb: "PCNETTP0020.jpg"}, {fr: {description: "TP Link TL-WN8200ND Adaptateur sans-fil USB Haute Puissance 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WR842ND Multi-Function Wireless N Router 300Mbps', modelNum: "TL-WR842ND", UPC: "845973051617", cost: "30.05", isInPromo: false, price: "50.00", qty: 2, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0021", thumb: "PCNETTP0021.jpg"}, {fr: {description: "TP Link TL-WR842ND Routeur Multi-fonctions Sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WA830RE Wireless N Range Extender 300Mbps', modelNum: "TL-WA830RE", UPC: "845973051686", cost: "34.35", isInPromo: false, price: "55.00", qty: 2, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0022", thumb: "PCNETTP0022.jpg"}, {fr: {description: "TP Link TL-WA830RE Range Extender sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WA901ND Wireless N Acces Point 300Mbps', modelNum: "TL-WA901ND", UPC: "845973051426", cost: "37.63", isInPromo: true, promoEnds: "10 sep 2015", price: "60.00", qty: 6, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0023", thumb: "PCNETTP0023.jpg"}, {fr: {description: "TP Link TL-WA901ND Point d'accès sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WR841HP High Power Wireless N Router 300Mbps', modelNum: "TL-WR841HP", UPC: "845973070625", cost: "38.65", isInPromo: false, price: "60.00", qty: 4, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0024", thumb: "PCNETTP0024.jpg"}, {fr: {description: "TP Link TL-WR841HP Routeur sans-fil Haute Puissance N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WR941ND Wireless N Router', modelNum: "TL-WR941ND", UPC: "845973051273", cost: "38.65", isInPromo: false, price: "60.00", qty: 18, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0025", thumb: "PCNETTP0025.jpg"}, {fr: {description: "TP Link TL-WR941ND Routeur sans-fil N"}}
		Products.insertTranslations {description: 'TP Link Archer T4U AC1200 Wireless Dual Band USB Adapter', modelNum: "Archer T4U", UPC: "845973050863", cost: "40.36", isInPromo: false, price: "60.00", qty: 4, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0026", thumb: "PCNETTP0026.jpg"}, {fr: {description: "TP Link Archer T4U AC1200 Adaptateur USB sans-fil bi-bande"}}
		Products.insertTranslations {description: 'TP Link TL-WA901ND Wireless N Acces Point 300Mbps', modelNum: "TL-WA901ND", UPC: "845973051426", cost: "42.95", isInPromo: false, price: "65.00", qty: 6, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0027", thumb: "PCNETTP0027.jpg"}, {fr: {description: "TP Link TL-WA901ND Point d'accès sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WR1043ND Wireless N Gigabit Router', modelNum: "TL-WR1043ND", UPC: "845973051389", cost: "45.11", isInPromo: true, promoEnds: "10 sep 2015", price: "65.00", qty: 10, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0028", thumb: "PCNETTP0028.jpg"}, {fr: {description: "TP Link TL-WR1043ND Routeur sans-fil N Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link TL-WDR3500 N600 Wireless Dual Band Router', modelNum: "TL-WDR3500", UPC: "845973070113", cost: "47.23", isInPromo: false, price: "70.00", qty: 70, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0029", thumb: "PCNETTP0029.jpg"}, {fr: {description: "TP Link TL-WDR3500 N600 Routeur sans-fil bi-bande"}}
		Products.insertTranslations {description: 'TP Link TL-WR1043ND Wireless N Gigabit Router', modelNum: "TL-WR1043ND", UPC: "845973051389", cost: "51.53", isInPromo: false, price: "75.00", qty: 10, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0030", thumb: "PCNETTP0030.jpg"}, {fr: {description: "TP Link TL-WR1043ND Routeur sans-fil N Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link Archer C20i AC750 Wireless Dual Band Router', modelNum: "ARCHER C20I", UPC: "845973071394", cost: "51.53", isInPromo: false, price: "75.00", qty: 48, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0031", thumb: "PCNETTP0031.jpg"}, {fr: {description: "TP Link Archer C20i AC750 Routeur sans-fil bi-bande"}}
		Products.insertTranslations {description: 'TP Link Archer C2 AC750 Wireless Dual Band Router Gigabit', modelNum: "ARCHER C2", UPC: "845973050962", cost: "51.73", isInPromo: true, promoEnds: "10 sep 2015", price: "75.00", qty: 16, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0032", thumb: "PCNETTP0032.jpg"}, {fr: {description: "TP Link Archer C2 AC750 Routeur sans-fil bi-bande Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link TL-WDR3600 N600 Wireless Dual Band Gigabit Router', modelNum: "TL-WDR3600", UPC: "845973070007", cost: "55.83", isInPromo: false, price: "80.00", qty: 16, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0033", thumb: "PCNETTP0033.jpg"}, {fr: {description: "TP Link TL-WDR3600 N600 Routeur sans-fil bi-bande Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link TL-WDR4300 N750 Wireless Dual Band Gigabit Router', modelNum: "TL-WDR4300", UPC: "845973051938", cost: "57.99", isInPromo: true, promoEnds: "10 sep 2015", price: "85.00", qty: 34, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0034", thumb: "PCNETTP0034.jpg"}, {fr: {description: "TP Link TL-WDR4300 N750 Routeur sans-fil bi-bande Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link Archer C2 AC750 Wireless Dual Band Gigabit Router', modelNum: "ARCHER C2", UPC: "845973050962", cost: "60.13", isInPromo: false, price: "85.00", qty: 16, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0035", thumb: "PCNETTP0035.jpg"}, {fr: {description: "TP Link Archer C2 AC750 Routeur sans-fil bi-bande Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link TL-WA7510N Outdoor Wireless Access Point 5Ghz 150Mbps', modelNum: "TL-WA7510N", UPC: "845973051723", cost: "68.71", isInPromo: false, price: "95.00", qty: 6, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0036", thumb: "PCNETTP0036.jpg"}, {fr: {description: "TP Link TL-WA7510N Point d'accès sans-fil extérieur 5Ghz 150Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-WDR4300 N750 Wireless Dual Band Gigabit Router', modelNum: "TL-WDR4300", UPC: "845973051938", cost: "77.31", isInPromo: false, price: "100.00", qty: 34, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0037", thumb: "PCNETTP0037.jpg"}, {fr: {description: "TP Link TL-WDR4300 N750 Routeur sans-fil bi-bande Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link TL-WR2543ND Wireless Dual Band Wireless N Gigabit Router 450Mbps', modelNum: "TL-WR2543ND", UPC: "845973051563", cost: "79.46", isInPromo: false, price: "105.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0038", thumb: "PCNETTP0038.jpg"}, {fr: {description: "TP Link TL-WR2543ND Routeur sans-fil bi-bande N Gigaoctet 450Mbps"}}
		Products.insertTranslations {description: 'TP Link Archer C7 AC1750 Wireless Dual Band Wireless Gigabit Router', modelNum: "Archer C7", UPC: "845973070601", cost: "101.01", isInPromo: true, promoEnds: "10 sep 2015",price: "125.00", qty: 20, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0039", thumb: "PCNETTP0039.jpg"}, {fr: {description: "TP Link Archer C7 AC1750 Routeur sans-fil bi-bande Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link EAP120 N Ceiling Access Point', modelNum: "EAP120", UPC: "845973071837", cost: "103.07", isInPromo: false, price: "130.00", qty: 3, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0040", thumb: "PCNETTP0040.jpg"}, {fr: {description: "TP Link EAP120 Point d'accès N de plafond"}}
		Products.insertTranslations {description: 'TP Link Archer C7 AC1750 Wireless Dual Band Wireless Gigabit Router', modelNum: "Archer C7", UPC: "845973070601", cost: "111.67", isInPromo: false, price: "150.00", qty: 20, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0041", thumb: "PCNETTP0041.jpg"}, {fr: {description: "TP Link Archer C7 AC1750 Routeur sans-fil bi-bande Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link Archer C8 AC1750 Wireless Dual Band Gigabit Router', modelNum: "Archer C8", UPC: "845973080013", cost: "137.43", isInPromo: false, price: "175.00", qty: 18, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0042", thumb: "PCNETTP0042.jpg"}, {fr: {description: "TP Link Archer C8 AC1750 Routeur sans-fil bi-bande Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link TD-8616 ADSL2+ Modem', modelNum: "TD-8616", UPC: "845973060220", cost: "19.39", isInPromo: false, price: "35.00", qty: 7, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0043", thumb: "PCNETTP0043.jpg"}, {fr: {description: "TP Link TD-8616 ADSL2+ Modem"}}
		Products.insertTranslations {description: 'TP Link TD-W8951ND Wireless N ADSL2+ Modem Router 150Mbps', modelNum: "TD-W8951ND", UPC: "845973060411", cost: "34.35", isInPromo: false, price: "55.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0044", thumb: "PCNETTP0044.jpg"}, {fr: {description: "TP Link TD-W8951ND Modem Routeur sans-fil N ADSL2+ 150Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-MR3020 Portable 3G/4G Wireless N Router', modelNum: "TL-MR3020", UPC: "845973051709", cost: "34.35", isInPromo: false, price: "55.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0045", thumb: "PCNETTP0045.jpg"}, {fr: {description: "TP Link TL-MR3020 Router sans-fil portable N 3G/4G"}}
		Products.insertTranslations {description: 'TP Link TD-W8961ND Wireless N ADSL2+ Modem Router 300Mbps', modelNum: "TD-W8961ND", UPC: "845973060435", cost: "38.65", isInPromo: false, price: "60.00", qty: 12, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0046", thumb: "PCNETTP0046.jpg"}, {fr: {description: "TP Link TD-W8961ND Modem Routeur sans-fil N ADSL2+ 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TL-MR3420 3G/4G Wireless N Router', modelNum: "TL-MR3420", UPC: "845973051495", cost: "38.65", isInPromo: false, price: "60.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0047", thumb: "PCNETTP0047.jpg"}, {fr: {description: "TP Link TL-MR3420 Routeur sans-fil N 3G/4G"}}
		Products.insertTranslations {description: 'TP Link TD-W8970 Wirekess N Gigabit ADSL2+ Modem Router 300Mbps', modelNum: "TD-W8970", UPC: "845973060862", cost: "68.71", isInPromo: false, price: "90.00", qty: 2, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0048", thumb: "PCNETTP0048.jpg"}, {fr: {description: "TP Link TD-W8970 Modem Routeur sans-fil N Gigaoctet 300Mbps"}}
		Products.insertTranslations {description: 'TP Link TD-W8980 N600 Wireless Dual Band Gigabit ADSL2+ Modem Router', modelNum: "TD-W8980", UPC: "845973060886", cost: "103.07", isInPromo: false, price: "140.00", qty: 10, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0049", thumb: "PCNETTP0049.jpg"}, {fr: {description: "TP Link TD-W8980 N600 Modem Routeur sans-fil bi-bande Gigaoctet ADSL2+"}}
		Products.insertTranslations {description: 'TP Link 2.4GHz 8dBi Indoor Omni-directional Antenna', modelNum: "TL-ANT2408CL", UPC: "845973052195", cost: "7.72", isInPromo: false, price: "20.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0050", thumb: "PCNETTP0050.jpg"}, {fr: {description: "TP Link Antenne omnidirectionnelle d'intérieur 8dBi pour réseaux 2.4GHz"}}
		Products.insertTranslations {description: 'TP Link 5 Meters Antenna Extension Cable', modelNum: "TL-ANT24EC5S", UPC: "845973052058", cost: "14.60", isInPromo: false, price: "30.00", qty: 3, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0051", thumb: "PCNETTP0051.jpg"}, {fr: {description: "TP Link Câble d'extension pour antenne de 5 mètres"}}
		Products.insertTranslations {description: 'TP Link Pigtail Cable', modelNum: "TL-ANT24PT3", UPC: "845973052218", cost: "14.60", isInPromo: false, price: "30.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0052", thumb: "PCNETTP0052.jpg"}, {fr: {description: "TP Link Câble pigtail"}}
		Products.insertTranslations {description: 'TP Link Surge Protector', modelNum: "TL-ANT24SP", UPC: "845973052072", cost: "16.16", isInPromo: false, price: "35.00", qty: 2, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0053", thumb: "PCNETTP0053.jpg"}, {fr: {description: "TP Link Protection contre les surtensions"}}
		Products.insertTranslations {description: 'TP Link PoE Injector', modelNum: "TL-PoE150S", UPC: "845973030506", cost: "21.47", isInPromo: false, price: "35.00", qty: 198, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0054", thumb: "PCNETTP0054.jpg"}, {fr: {description: "TP Link Injecteur PoE"}}
		Products.insertTranslations {description: 'TP Link 2.4GHz 9dBi Directional Antenna', modelNum: "TL-ANT2409A", UPC: "845973052034", cost: "24.04", isInPromo: false, price: "40.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0055", thumb: "PCNETTP0055.jpg"}, {fr: {description: "TP Link Antenne directionnelle 9dBi pour réseaux 2.4 GHz"}}
		Products.insertTranslations {description: 'TP Link 12 Meters Low-loss Antenna Extension Cable', modelNum: "TL-ANT24EC12N", UPC: "845973052102", cost: "42.95", isInPromo: false, price: "60.00", qty: 3, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0056", thumb: "PCNETTP0056.jpg"}, {fr: {description: "Câble d'extension à faible perte pour antenne de 12 mètres"}}
		Products.insertTranslations {description: 'TP Link 2.4GHz 12dBi Outdoor Omni-directional Antenna', modelNum: "TL-ANT2412D", UPC: "845973052157", cost: "42.95", isInPromo: false, price: "60.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0057", thumb: "PCNETTP0057.jpg"}, {fr: {description: "TP Link Antenne omnidirectionnelle d'extérieur 12dBi pour réseaux 2.4GHz"}}
		Products.insertTranslations {description: 'TP Link 8-Port 10/100Mbps Desktop Switch with 4-Port PoE', modelNum: "TL-SF1008P", UPC: "845973020682", cost: "60.13", isInPromo: false, price: "80.00", qty: 18, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0058", thumb: "PCNETTP0058.jpg"}, {fr: {description: "TP Link Switch de bureau 8 ports 10/100Mbps - 4 Ports PoE"}}
		Products.insertTranslations {description: 'TP Link Gigabit PCI Network Adapter', modelNum: "TG-3269", UPC: "845973001001", cost: "10.30", isInPromo: false, price: "10.30", qty: 5, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0059", thumb: "PCNETTP0059.jpg"}, {fr: {description: "TP Link Adaptateur réseau Gigabit PCI"}}
		Products.insertTranslations {description: 'TP Link Wireless N PCI Express Adapter 150Mbps', modelNum: "TL-WN781ND", UPC: "845973050511", cost: "13.73", isInPromo: false, price: "30.00", qty: 3, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0060", thumb: "PCNETTP0060.jpg"}, {fr: {description: "TP Link Adaptateur PCI Express sans-fil N 150Mbps"}}
		Products.insertTranslations {description: 'TP Link Wireless N PCI Express Adapter 300Mbps', modelNum: "TL-WN881ND", UPC: "845973050573", cost: "13.98", isInPromo: true, promoEnds: "10 sep 2015", price: "30.00", qty: 9, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0061", thumb: "PCNETTP0061.jpg"}, {fr: {description: "TP Link Adaptateur PCI Express sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link Wireless N PCI Express Adapter 300Mbps', modelNum: "TL-WN881ND", UPC: "845973050573", cost: "17.17", isInPromo: false, price: "35.00", qty: 9, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0062", thumb: "PCNETTP0062.jpg"}, {fr: {description: "TP Link Adaptateur PCI Express sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link Wireless N PCI Adapter 300Mbps', modelNum: "TL-WN851ND", UPC: "845973050641", cost: "21.47", isInPromo: false, price: "40.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0063", thumb: "PCNETTP0063.jpg"}, {fr: {description: "TP Link Adaptateur PCI sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link Wireless N PCI Adapter 300Mbps', modelNum: "TL-WN951N", UPC: "845973050344", cost: "28.29", isInPromo: false, price: "45.00", qty: 11, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0064", thumb: "PCNETTP0064.jpg"}, {fr: {description: "TP Link Adaptateur PCI sans-fil N 300Mbps"}}
		Products.insertTranslations {description: 'TP Link N600 Wireless Dual Band PCI Express Adapter', modelNum: "TL-WDN3800", UPC: "845973050771", cost: "34.35", isInPromo: false, price: "50.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0065", thumb: "PCNETTP0065.jpg"}, {fr: {description: "TP Link N600 Adaptateur PCI Express bi-bande sans-fil"}}
		Products.insertTranslations {description: 'TP Link N900 Wireless Dual Band PCI Express Adapter', modelNum: "TL-WDN4800", UPC: "845973050603", cost: "36.52", isInPromo: true, promoEnds: "10 sep 2015", price: "55.00", qty: 5, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0066", thumb: "PCNETTP0066.jpg"}, {fr: {description: "TP Link Adaptateur PCI Express bi-bande sans-fil N 450Mbps"}}
		Products.insertTranslations {description: 'TP Link N900 Wireless Dual Band PCI Express Adapter', modelNum: "TL-WDN4800", UPC: "845973050603", cost: "42.95", isInPromo: false, price: "60.00", qty: 5, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0067", thumb: "PCNETTP0067.jpg"}, {fr: {description: "TP Link Adaptateur PCI Express bi-bande sans-fil N 450Mbps"}}
		Products.insertTranslations {description: 'TP Link Archer T8E Wireless N PCI Express Adapter', modelNum: "ARCHER T8E", UPC: "845973050771", cost: "77.31", isInPromo: false, price: "100.00", qty: 0, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0068", thumb: "PCNETTP0068.jpg"}, {fr: {description: "TP Link Archer T8E Adaptateur PCI Express sans-fil N"}}
		Products.insertTranslations {description: 'TP Link AV200 Nano Powerline Adapter Starter Kit', modelNum: "TL-PA2010KIT", UPC: "845973031961", cost: "30.05", isInPromo: false, price: "45.00", qty: 30, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0069", thumb: "PCNETTP0069.jpg"}, {fr: {description: "TP Link AV200 Kit de démarrage Nano adaptateur CPL"}}
		Products.insertTranslations {description: 'TP Link Nano Powerline Kit (2 units)', modelNum: "TL-PA4010KIT", UPC: "845973032029", cost: "32.35", isInPromo: true, price: "50.00", qty: 0, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0070", thumb: "PCNETTP0070.jpg"}, {fr: {description: "TP Link AV500 Kit de démarrage Nano adaptateur CPL (2 unités)"}}
		Products.insertTranslations {description: 'TP Link Nano Powerline Kit (2 units)', modelNum: "TL-PA4010KIT", UPC: "845973032029", cost: "42.95", isInPromo: false, price: "60.00", qty: 0, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0071", thumb: "PCNETTP0071.jpg"}, {fr: {description: "TP Link AV500 Kit de démarrage Nano adaptateur CPL (2 unités)"}}
		Products.insertTranslations {description: 'TP Link AV500 WiFi Powerline Extender Starter Kit 300Mbps', modelNum: "TL-WPA4220KIT", UPC: "845973032579", cost: "48.07", isInPromo: true, price: "70.00", qty: 29, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0072", thumb: "PCNETTP0072.jpg"}, {fr: {description: "TP Link AV500 Kit extenseur CPL Wi-Fi N 300Mbps (powerline)"}}
		Products.insertTranslations {description: 'TP Link AV500 WiFi Powerline Extender Starter Kit 300Mbps', modelNum: "TL-WPA4220KIT", UPC: "845973032579", cost: "64.41", isInPromo: false, price: "90.00", qty: 29, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0073", thumb: "PCNETTP0073.jpg"}, {fr: {description: "TP Link AV500 Kit extenseur CPL Wi-Fi N 300Mbps (powerline)"}}
		Products.insertTranslations {description: 'TP Link Single Parallel Port Fast Ethernet Print Server', modelNum: "TL-PS110P", UPC: "845973031015", cost: "42.95", isInPromo: false, price: "70.00", qty: 5, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0074", thumb: "PCNETTP0074.jpg"}, {fr: {description: "TP Link Serveur d'impression Fast Ethernet avec un seul port parallèle"}}
		Products.insertTranslations {description: 'TP Link Single USB2.0 Port Fast Ethernet Print Server', modelNum: "TL-PS110U", UPC: "845973031008", cost: "42.95", isInPromo: false, price: "70.00", qty: 2, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0075", thumb: "PCNETTP0075.jpg"}, {fr: {description: "TP Link Serveur dimpression Fast Ethernet avec un seul port USB 2.0"}}
		Products.insertTranslations {description: 'TP Link Pocket-Sized Wireless Print Server 150Mbps', modelNum: "TL-WPS510U", UPC: "845973031039", cost: "68.71", isInPromo: false, price: "90.00", qty: 1, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0076", thumb: "PCNETTP0076.jpg"}, {fr: {description: "TP Link Serveur d'impression de poche sans-fil 150Mbps"}}
		Products.insertTranslations {description: 'TP Link 16-Port Gigabit Easy Smart Switch', modelNum: "TL-SG1016DE", UPC: "845973021269", cost: "103.07", isInPromo: false, price: "125.00", qty: 2, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0077", thumb: "PCNETTP0077.jpg"}, {fr: {description: "TP Link Easy Smart Switch 16 ports Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link 24-Port Gigabit Easy Smart Switch', modelNum: "TL-SG1024DE", UPC: "845973021245", cost: "146.03", isInPromo: false, price: "166.00", qty: 3, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0078", thumb: "PCNETTP0078.jpg"}, {fr: {description: "TP Link Easy Smart Switch 24 ports Gigaoctet"}}
		Products.insertTranslations {description: 'TP Link 16-Port Pure-Gigabit Smart Switch', modelNum: "TL-SG2216", UPC: "845973021085", cost: "128.85", isInPromo: false, price: "150.00", qty: 3, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0079", thumb: "PCNETTP0079.jpg"}, {fr: {description: "TP Link Smart Switch Gigaoctet pur"}}
		Products.insertTranslations {description: 'TP Link 5-Port 10/100Mbps Desktop Switch', modelNum: "TL-SF1005D", UPC: "845973020064", cost: "10.30", isInPromo: false, price: "22.00", qty: 10, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0080", thumb: "PCNETTP0080.jpg"}, {fr: {description: "TP Link Switch de bureau 5 ports 10/100Mbps"}}
		Products.insertTranslations {description: 'TP Link Gigabit PCI Express Network Adapter', modelNum: "TG-3468", UPC: "845973001049", cost: "11.69", isInPromo: false, price: "23.00", qty: 15, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0081", thumb: "PCNETTP0081.jpg"}, {fr: {description: "TP Link Adaptateur réseau Gigaoctet PCI Express"}}
		Products.insertTranslations {description: 'TP Link 8-Port 10/100Mbps Desktop Switch', modelNum: "TL-SF1008D", UPC: "845973020071", cost: "14.60", isInPromo: false, price: "28.00", qty: 8, catRel: "PC", subCatRel: "NET", manufRel: "TP", systemId: "PCNETTP0082", thumb: "PCNETTP0082.jpg"}, {fr: {description: "TP Link Switch de bureau 8 ports 10/100Mbps"}}
